replicaCount: 1
image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: "v1.11.0"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: ""
  annotations: {}
  host: localhost
  path: /whoami
  pathType: Prefix
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
